<?php
/**
 *
 */
/** @var $block \Mageplaza\BannerSlider\Block\Adminhtml\Banner\Edit\Form */
?>
<div class="entry-edit form-inline" id="mageplaza-bannerslider">
    <?= $block->getFormHtml(); ?>
</div>
<?= $block->getChildHtml('form_after'); ?>

<script type="text/x-magento-init">
    {
        "#mageplaza-bannerslider": {
            "Mageplaza_BannerSlider/js/view/bannerslider":{
                "templateHtml": "<?= $block->escapeJs($block->getTemplateHtml()); ?>",
                "imgUrls": "<?= $block->escapeJs($block->getImageUrls()); ?>"
            }
        }
    }
</script>